changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - github-actions
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
    - title: Changes
      labels:
        - change
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Dependencies
      labels:
        - dependencies
    - title: Developer / Repository
      labels:
        - repository
        - dev
        - ci
    - title: Other Changes
      labels:
        - '*'
