use std::any::TypeId;
use std::collections::HashSet;
use std::fs;
use std::path::Path;

use ts_rs::{Config, TS, TypeVisitor};

struct ContractTypes<'a> {
    config: &'a Config,
    seen: HashSet<TypeId>,
    declarations: Vec<String>,
}

impl ContractTypes<'_> {
    fn add<T: TS + 'static + ?Sized>(&mut self) {
        if T::output_path().is_none() || !self.seen.insert(TypeId::of::<T>()) {
            return;
        }
        self.declarations.push(format!("export {}", T::decl(self.config)));
        T::visit_dependencies(self);
    }
}

impl TypeVisitor for ContractTypes<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        self.add::<T>();
    }
}

pub fn export_api_contract(output: &Path) {
    let config = Config::default();
    let mut types = ContractTypes { config: &config, seen: HashSet::new(), declarations: Vec::new() };

    macro_rules! export_root {
        ($type:ty) => {
            types.add::<$type>();
        };
    }

    export_root!(crate::app::AppEvent);
    export_root!(crate::run_library::RunsResponse);
    export_root!(crate::run_library::ManualRunRequest);
    export_root!(crate::run_library::EliteImportResponse);
    export_root!(ge_catalog::run_catalog::RunSort);
    export_root!(crate::desktop::folders::FolderPickResponse);
    export_root!(crate::desktop::folders::FolderValidation);
    export_root!(crate::diagnostics::matching::MatchResponse);
    export_root!(crate::run_monitoring::RecordingOptions);
    export_root!(ge_catalog::statistics::StatisticsData);
    export_root!(ge_catalog::statistics::MonitoringSessionSummary);
    export_root!(ge_catalog::statistics::MonitoringSessionDetail);
    types.declarations.sort_unstable();

    let mut source = format!(
        "// Generated by ge_runtime. Do not edit.\n\nimport type {{ AppSettings }} from './settings';\n\nexport type DifficultyNumber = 0 | 1 | 2 | 3;\n\nexport type StatisticsBucket = 'day' | 'week' | 'month' | 'year';\n\n{}\n",
        types.declarations.join("\n\n")
    );
    source = source.lines().map(str::trim_end).collect::<Vec<_>>().join("\n");
    source.push('\n');
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("create generated API directory");
    }
    fs::write(output, source).expect("write generated API bindings");
}
