use std::fs;
use std::path::Path;

use ts_rs::{Config, TS};

fn make_field_optional(source: &mut String, type_name: &str, field_name: &str) {
    let declaration = format!("export type {type_name} = {{");
    let start = source.find(&declaration).unwrap_or_else(|| panic!("missing generated type {type_name}"));
    let end = start + source[start..].find("};").unwrap_or_else(|| panic!("unterminated generated type {type_name}"));
    let field = format!("{field_name}: ");
    let offset =
        source[start..end].find(&field).unwrap_or_else(|| panic!("missing generated field {type_name}.{field_name}"));
    source.insert(start + offset + field_name.len(), '?');
}

pub fn export_api_contract(output: &Path) {
    let config = Config::default();
    let mut declarations = Vec::new();

    macro_rules! export {
        ($type:ty) => {
            declarations.push(format!("export {}", <$type>::decl(&config)));
        };
    }

    export!(ge_clip::RunStatus);
    export!(ge_clip::RomVersion);
    export!(ge_clip::ClipMetadata);
    export!(ge_game::Times);
    export!(ge_cv::ActivePictureRegion);
    export!(ge_cv::BlackFrameSignal);
    export!(ge_cv::Screen);
    export!(ge_cv::MatchRegion);
    export!(ge_cv::AnnotationRect);
    export!(ge_cv::AnnotationSet);
    export!(ge_cv::LevelMatch);
    export!(ge_catalog::run_catalog::RunRetentionState);
    export!(ge_catalog::run_catalog::RunSort);
    export!(ge_catalog::YoutubeAssociationSource);
    export!(ge_catalog::YoutubeMetadata);
    export!(ge_catalog::UploadHistoryEntry);
    export!(ge_catalog::statistics::StatusCounts);
    export!(ge_catalog::statistics::StatisticsRange);
    export!(ge_catalog::statistics::DifficultyCombinedBest);
    export!(ge_catalog::statistics::CombinedBestTimes);
    export!(ge_catalog::statistics::StatisticsSummary);
    export!(ge_catalog::statistics::LevelDifficultyCounts);
    export!(ge_catalog::statistics::LevelCounts);
    export!(ge_catalog::statistics::BucketCounts);
    export!(ge_catalog::statistics::RunTimePoint);
    export!(ge_catalog::statistics::SelectedCohort);
    export!(ge_catalog::statistics::StatisticsData);
    export!(ge_catalog::statistics::MonitoringSessionSummary);
    export!(ge_catalog::statistics::SessionAttempt);
    export!(ge_catalog::statistics::MonitoringSessionDetail);
    export!(crate::http::routes::sources::Source);
    export!(crate::http::routes::runs::RunDirectoryKind);
    export!(crate::http::routes::runs::RunDirectoryScan);
    export!(crate::http::routes::runs::RunClip);
    export!(crate::http::routes::runs::RunsResponse);
    export!(crate::http::routes::runs::ManualRunRequest);
    export!(crate::http::routes::runs::EliteImportResponse);
    export!(crate::http::routes::record::ReplayBufferStatus);
    export!(crate::http::routes::folders::FolderPickResponse);
    export!(crate::http::routes::folders::FolderValidation);
    export!(crate::http::routes::matcher::MatchResponse);
    export!(crate::recording::RecordingOptions);
    export!(crate::settings::SettingsStatus);
    export!(crate::updates::PluginUpdate);
    export!(crate::updates::UpdatePhase);
    export!(crate::updates::UpdateStatus);
    export!(crate::youtube::YoutubeAccount);
    export!(crate::youtube::YoutubeUploadState);
    export!(crate::youtube::YoutubeUploadStatus);
    export!(crate::youtube::YoutubeStatus);
    export!(crate::http::MonitorWallClockState);
    export!(crate::http::LevelTimerStartReason);
    export!(crate::http::LevelTimerPhase);
    export!(crate::http::MonitorSnapshot);
    export!(crate::http::RunCatalogSync);
    export!(crate::http::MonitorStoppedReason);
    export!(crate::http::MonitorFpsHealth);
    export!(crate::http::MonitorFps);
    export!(crate::http::RecordingStatus);
    export!(crate::http::ReplaySaveStage);
    export!(crate::http::ReplaySaveStatus);
    export!(crate::http::RecordingSavePending);
    export!(crate::http::RecordingSaved);
    export!(crate::http::AppSnapshot);
    export!(crate::http::AppEvent);

    let mut source = format!(
        "// Generated by ge_rust. Do not edit.\n\nimport type {{ AppSettings }} from './settings';\n\nexport type DifficultyNumber = 0 | 1 | 2 | 3;\n\nexport type StatisticsBucket = 'day' | 'week' | 'month' | 'year';\n\n{}\n",
        declarations.join("\n\n")
    );

    // Keep compatibility with browser-created partial records and fields omitted by serde.
    for (type_name, field_name) in [
        ("ClipMetadata", "wasPersonalBest"),
        ("ClipMetadata", "retentionState"),
        ("LevelMatch", "raw_times"),
        ("LevelMatch", "match_regions"),
        ("LevelMatch", "annotation_sets"),
        ("RunsResponse", "nextCursor"),
        ("RunDirectoryScan", "error"),
        ("RunClip", "modified"),
        ("RunClip", "durationSecs"),
        ("RunClip", "youtube"),
    ] {
        make_field_optional(&mut source, type_name, field_name);
    }
    source = source.lines().map(str::trim_end).collect::<Vec<_>>().join("\n");
    source.push('\n');
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).expect("create generated API directory");
    }
    fs::write(output, source).expect("write generated API bindings");
}
