# Rust static library build.
#
# Defines the `rust_build` custom target (cargo build) and the `rust_libs`
# imported target that the core links against. Must be included after
# OpenCVStatic (it inherits the OPENCV_* probe vars in RUST_BUILD_ENV) and
# Frontend (rust_build depends on browser_build).

set(RUST_DIR "${CMAKE_CURRENT_SOURCE_DIR}/rust")

# Built up as a CMake list so each flag expands to a separate cargo argument.
set(CARGO_BUILD_FLAGS "")
if(WIN32)
  # Windows package builds only need the staticlib that CMake links into
  # golden_core. Binaries/tests link Rust directly and therefore cannot resolve
  # OBS bridge symbols such as ge_obs_collect_source_names until golden_core is
  # linked.
  list(APPEND CARGO_BUILD_FLAGS --lib)
else()
  list(APPEND CARGO_BUILD_FLAGS --all-targets)
endif()
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
  set(RUST_PROFILE "debug")
else()
  set(RUST_PROFILE "release")
  list(APPEND CARGO_BUILD_FLAGS --release)
endif()

# Enable the crate's `dev` feature (permissive CORS) when serving the SPA from
# the separate-origin Vite dev server.
if(BROWSER_DEV)
  list(APPEND CARGO_BUILD_FLAGS --features dev)
endif()

set(GE_BROWSER_DEV_URL "http://localhost:${BROWSER_DEV_PORT}")

if(WIN32)
  set(RUST_LIB "${RUST_DIR}/target/${RUST_PROFILE}/ge_rust.lib")
else()
  set(RUST_LIB "${RUST_DIR}/target/${RUST_PROFILE}/libge_rust.a")
endif()

# https://github.com/twistedfall/opencv-rust/blob/master/INSTALL.md#macos-package
if(APPLE)
  # Get the active developer directory (works for both Xcode and Command Line Tools)
  execute_process(
        COMMAND xcode-select --print-path
        OUTPUT_VARIABLE XCODE_DEVELOPER_DIR
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

  # 1. Define the two possible paths where libclang.dylib could live
  set(CLANG_PATH_XCODE "${XCODE_DEVELOPER_DIR}/Toolchains/XcodeDefault.xctoolchain/usr/lib")
  set(CLANG_PATH_CLT "${XCODE_DEVELOPER_DIR}/usr/lib")

  # 2. Determine which path actually exists on the machine
  if(EXISTS "${CLANG_PATH_XCODE}")
    set(CHOSEN_DYLD_PATH "${CLANG_PATH_XCODE}")
  elseif(EXISTS "${CLANG_PATH_CLT}")
    set(CHOSEN_DYLD_PATH "${CLANG_PATH_CLT}")
  else()
    message(FATAL_ERROR "Neither Xcode nor Command Line Tools, try running `xcode-select --install` first.")
  endif()

  # 3. Append to your Rust environment list
  list(APPEND RUST_BUILD_ENV
        "DYLD_FALLBACK_LIBRARY_PATH=${CHOSEN_DYLD_PATH}"
        "LDFLAGS=-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"
        "LD_LIBRARY_PATH=$ENV{LD_LIBRARY_PATH}:/usr/local/lib"
    )

  if(CMAKE_OSX_DEPLOYMENT_TARGET)
    list(APPEND RUST_BUILD_ENV "MACOSX_DEPLOYMENT_TARGET=${CMAKE_OSX_DEPLOYMENT_TARGET}")
  endif()
endif()

set(RUST_CARGO_ENV
      "BROWSER_BUNDLE=${BROWSER_BUNDLE}"
      "GE_PLUGIN_VERSION=${GE_PLUGIN_VERSION}"
      "GE_BROWSER_DEV_URL=${GE_BROWSER_DEV_URL}"
      ${RUST_BUILD_ENV})

set(RUST_CARGO_ENV_FILE "${CMAKE_CURRENT_BINARY_DIR}/rust-cargo-env.sh")
file(WRITE "${RUST_CARGO_ENV_FILE}"
     "# Generated by CMake. Source this before direct cargo commands for ge_rust.\n")
foreach(_env ${RUST_CARGO_ENV})
  if(NOT _env MATCHES "^([^=]+)=(.*)$")
    message(FATAL_ERROR "Invalid Rust cargo environment entry: ${_env}")
  endif()
  set(_env_name "${CMAKE_MATCH_1}")
  set(_env_value "${CMAKE_MATCH_2}")
  string(REPLACE "'" "'\"'\"'" _env_value_quoted "${_env_value}")
  file(APPEND "${RUST_CARGO_ENV_FILE}" "export ${_env_name}='${_env_value_quoted}'\n")
endforeach()

function(ge_json_escape out value)
  string(REPLACE "\\" "\\\\" _escaped "${value}")
  string(REPLACE "\"" "\\\"" _escaped "${_escaped}")
  set(${out} "${_escaped}" PARENT_SCOPE)
endfunction()

get_filename_component(GE_REPO_ROOT "${CMAKE_CURRENT_SOURCE_DIR}" DIRECTORY)
set(RUST_ANALYZER_ENV ${RUST_CARGO_ENV}
      "CARGO_TARGET_DIR=${RUST_DIR}/target/rust-analyzer")
set(RUST_ANALYZER_SETTINGS_FILE "${CMAKE_CURRENT_BINARY_DIR}/vscode-settings.json")
file(WRITE "${RUST_ANALYZER_SETTINGS_FILE}"
     "{\n"
     "  \"rust-analyzer.linkedProjects\": [\"${GE_REPO_ROOT}/obs2/rust/Cargo.toml\"],\n"
     "  \"rust-analyzer.cargo.extraEnv\": {\n")
list(LENGTH RUST_ANALYZER_ENV _ra_env_len)
math(EXPR _ra_env_last "${_ra_env_len} - 1")
foreach(_i RANGE 0 ${_ra_env_last})
  list(GET RUST_ANALYZER_ENV ${_i} _env)
  if(NOT _env MATCHES "^([^=]+)=(.*)$")
    message(FATAL_ERROR "Invalid rust-analyzer environment entry: ${_env}")
  endif()
  set(_env_name "${CMAKE_MATCH_1}")
  set(_env_value "${CMAKE_MATCH_2}")
  ge_json_escape(_env_name_json "${_env_name}")
  ge_json_escape(_env_value_json "${_env_value}")
  if(_i EQUAL _ra_env_last)
    set(_comma "")
  else()
    set(_comma ",")
  endif()
  file(APPEND "${RUST_ANALYZER_SETTINGS_FILE}"
       "    \"${_env_name_json}\": \"${_env_value_json}\"${_comma}\n")
endforeach()
file(APPEND "${RUST_ANALYZER_SETTINGS_FILE}" "  }\n}\n")

set(ZED_SETTINGS_FILE "${CMAKE_CURRENT_BINARY_DIR}/zed-settings.json")
file(WRITE "${ZED_SETTINGS_FILE}"
     "{\n"
     "  \"lsp\": {\n"
     "    \"clangd\": {\n"
     "      \"initialization_options\": {\n"
     "        \"compilationDatabasePath\": \"obs2/build\"\n"
     "      }\n"
     "    },\n"
     "    \"rust-analyzer\": {\n"
     "      \"initialization_options\": {\n"
     "        \"linkedProjects\": [\"${GE_REPO_ROOT}/obs2/rust/Cargo.toml\"],\n"
     "        \"cargo\": {\n"
     "          \"extraEnv\": {\n")
foreach(_i RANGE 0 ${_ra_env_last})
  list(GET RUST_ANALYZER_ENV ${_i} _env)
  if(NOT _env MATCHES "^([^=]+)=(.*)$")
    message(FATAL_ERROR "Invalid rust-analyzer environment entry: ${_env}")
  endif()
  set(_env_name "${CMAKE_MATCH_1}")
  set(_env_value "${CMAKE_MATCH_2}")
  ge_json_escape(_env_name_json "${_env_name}")
  ge_json_escape(_env_value_json "${_env_value}")
  if(_i EQUAL _ra_env_last)
    set(_comma "")
  else()
    set(_comma ",")
  endif()
  file(APPEND "${ZED_SETTINGS_FILE}"
       "            \"${_env_name_json}\": \"${_env_value_json}\"${_comma}\n")
endforeach()
file(APPEND "${ZED_SETTINGS_FILE}"
     "          }\n"
     "        }\n"
     "      }\n"
     "    }\n"
     "  }\n"
     "}\n")

if(GE_REUSE_HOST_BUILD_INPUTS)
  add_custom_target(rust_build ALL
      COMMAND ${CMAKE_COMMAND} -E echo "Using existing Rust static library at ${RUST_LIB}"
      COMMAND ${CMAKE_COMMAND}
              "-DGE_REQUIRED_FILE=${RUST_LIB}"
              -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/check-file-exists.cmake"
      COMMAND ${CMAKE_COMMAND}
              "-DGE_REQUIRED_FILE=${CMAKE_CURRENT_SOURCE_DIR}/ge_rust.h"
              -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/check-file-exists.cmake"
      VERBATIM
  )
else()
  add_custom_target(rust_build ALL
      COMMAND ${CMAKE_COMMAND} -E env
              ${RUST_CARGO_ENV}
              cargo build ${CARGO_BUILD_FLAGS}
      WORKING_DIRECTORY "${RUST_DIR}"
      COMMENT "Building Rust static library (${RUST_PROFILE})"
      VERBATIM
  )
endif()

# The Rust crate embeds browser/build/index.html via include_str!, so the
# frontend must be built (successfully) first. This also guarantees that a
# failed browser_build stops the whole build before cargo runs.
add_dependencies(rust_build browser_build)

# Declare an imported target so we can add it to target_link_libraries.
add_library(rust_libs STATIC IMPORTED GLOBAL)
set_target_properties(rust_libs PROPERTIES
    IMPORTED_LOCATION "${RUST_LIB}"
)
add_dependencies(rust_libs rust_build)
