name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - youtube-oauth-verification

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build-packages.yml
    secrets: inherit
