name: CI

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-packages.yml
    secrets: inherit
    with:
      package-profile: true
      publish-vcpkg-cache: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
